#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/1724bea1-fc71-463d-aea0-53dd8abce94d/ # 
title: validcustomers-proc-api
version: 1.0
mediaType: 
- application/json

traits:
  client_id_required:
    headers:
      client_id:
          type: string
          description: Client Id provided by API manager 
          required: true
      client_secret:
            type: string
            description: Client secret provided by API
            required: true

/validcustomer:
  get:
    is:
      - client_id_required:
    description: It gets the full profile of valid customers 
    responses:
      200:
        body:
          application/json:
            example: 
             {             
                "message": "valid customers" 
             }

      400:
        body:
          application/json:
            example:
              {
              "Message": "Not Valid"
              }
                      
      500:
        body:
          application/json:
            example:
              {
              "Message": " Server error"
              }
    
