#%RAML 1.0 Trait
queryParameters:
      order id:
        description: order id 
        type: integer
        required: false
      fullname:
        description: shows the fullname of the user
        type: string
        required: false
      username:
        description: shows the username parameters
        type: string
        required: false
        minLength: 3
        maxLength: 10
        default: Jhon