#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/0d0500a1-0714-4083-b7ef-78f369a190bb/ # 
title: craft-online-shopping
version: 1.0
mediaType: 
- application/json
uses:
  mylib: library.raml   
documentation:
  - !include documentation.raml

/users:
  get:
    description: gets all users
    responses:
      200:
        body:
          application/json:
            type: mylib.userdatatypes[]
            example: !include examples/users.json  
    is: 
    - mylib.traitresponse:
    - mylib.userquery:
      
  type: 
    mylib.collection:
      resourcedata: users
      resourcedatas: users  
      
  post:
    description: creates or notifies users
    responses:
      200:
        body:
          application/json:
            type: mylib.userdatatypes[]
            example: !include examples/users.json                   
    is: 
    - mylib.traitresponse:
    - mylib.postresponse:

  /{userid}:
    description: gets user by id
    get:     
      responses:
        200:
          body:
            application/json:
              type: mylib.userdatatypes[]
              example: !include examples/users.json 

      is: 
      - mylib.traitresponse:
      - mylib.userquery:

    type: 
      mylib.collection:
        resourcedata: user
        resourcedatas: user  
                    
/products:
  description: gets all products
  get:
    responses:
      200:
        body:
          application/json:
            type: mylib.productdatatypes[]
            example: !include examples/products.json
             
    is: 
    - mylib.traitresponse:
    - mylib.productquery:

  type: 
    mylib.collection:
      resourcedata: products
      resourcedatas: products  

  /{productid}:
    get:
      description: gets a specific product using the product ID
      responses:
        200:
          body:
            application/json:
              type: mylib.productdatatypes[]
              example: !include examples/products.json

    is: 
    - mylib.traitresponse:
    - mylib.productquery:

    type: 
      mylib.collection:
        resourcedata: product
        resourcedatas: product 

/orders:
  get:
    description: gets all orders
    responses:
      200:
        body:
          application/json:
            type: mylib.orderdatatypes[]
            example: !include examples/orders.json

    is: 
    - mylib.traitresponse:
    - mylib.orderquery:

  type: 
    mylib.collection:
      resourcedata: orders
      resourcedatas: orders   

  post:
    description: creates or modifies order
    responses:
      200:
        body:
          application/json:
            type: mylib.orderdatatypes[]
            example: !include examples/orders.json

    is: 
    - mylib.traitresponse:
    - mylib.postresponse:

  /{orderid}:
    get:
      description: gets a specific order using the order ID
      responses:
        200:
          body:
            application/json:
              type: mylib.orderdatatypes[]
              example: !include examples/orders.json
               
    is: 
    - mylib.traitresponse:
    - mylib.orderquery:

    type: 
      mylib.collection:
        resourcedata: order
        resourcedatas: order  

  /{userid}:
    get:
      description: gets all the orders of the user using the userid
      responses:
        200:
          body:
            application/json:
              type: mylib.orderdatatypes[]
              example: !include examples/orders.json
                
    is: 
    - mylib.traitresponse:
    - mylib.orderquery:

    type: 
      mylib.collection:
        resourcedata: order
        resourcedatas: order  
                  
/categories:
  get:
    description: fetches all the categories
    responses:
      200:
        body:
          application/json:
            type: mylib.categorydatatypes[]
            example: !include examples/category.json
            
    is: 
    - mylib.traitresponse:
    - mylib.categoryquery:

  type: 
      mylib.collection:
        resourcedata: category
        resourcedatas: category
      
  /{categoryid}:
    get:
      description: fetches a specific category using the category ID
      responses:
        200:
          body:
            application/json:
              type: mylib.categorydatatypes[]
              example: !include examples/category.json
          
    is: 
    - mylib.traitresponse:
    - mylib.categoryquery:

    type: 
      mylib.collection:
        resourcedata: category
        resourcedatas: category
