#%RAML 1.0 DocumentationItem
title: Online shopping document
content: This rest API contains several http methods and status codes
description: The purpose of a documentation is to give a brief clarification about the RAML.