#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/f671c8fa-40e6-4add-bbf9-e916f0aef7de/ # 
title: employee
version: 1.0
mediaType: 
- application/json

types:
  empdatatypes: !include datatypes/empDatatype.raml
traits:
  traitresponse: !include traits/employeetrait.raml
  empQuery: !include traits/empQuery.raml

/employee:
  get:
    description: gets all employee 
    responses:
      200:
        body:
          application/json:
            type: empdatatypes[]
            example: !include examples/empExample.raml
            
    is:
     - traitresponse:
     - empQuery:   

  post:
    description: creates new employee profile
    responses:
      201:
        body:
          application/json:
            example:
              {
                "message": "New employee profile created"
              }

  /{empid}:
    put:
      description: edits employee profile using ID 
      responses:
        200:
          body:
            application/json:
              example:
                {
                  "message": "Employee profile altered"
                }

    is:
     - traitresponse:
     - empQuery:  

    delete:
      description: deletes employee by ID 
      responses:
        200:
          body:
            application/json:
              example:
                {
                  "message": "Employee profile deleted"
                }

      is:
       - traitresponse:
       - empQuery:      
