#%RAML 1.0 Extension
extends: craft-online-shopping-c.raml
/admin:
  get:
  post:
  put:
  delete:
   
/Adminproduct:
  get:
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              message:
                {"resource deleted"}
      
/Adminusers:
  get:
  post:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              message:
                {"resource deleted"}
      

/Adminorders:
  get:
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              message:
                {"resource deleted"}
/Admincategories:
  get:
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              message:
                {"resource deleted"}      

